In [1]:
import torch
randint = torch.randint(-100,100,(6,))
print(randint)

tensor([ 70,  95, -16,  84, -12,  80])


In [2]:
tensor = torch.tensor([[0.1,1.2],[0.1,1.2],[0.1,1.2]])
print(tensor)

tensor([[0.1000, 1.2000],
        [0.1000, 1.2000],
        [0.1000, 1.2000]])


In [3]:
zeros = torch.zeros(2,3)
print(zeros)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
ones = torch.ones(3,4)
print(ones)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
input = torch.empty(2,4)
input

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

In [7]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [12]:
logspace = torch.logspace(start=-10,end=10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [13]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
a = torch.empty((2,3),dtype = torch.int64)
empty_like = torch.empty_like(a)

print(empty_like)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [15]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [21]:
import time
start_time = time.time()
zers = torch.zeros(1,1)
end_time = time.time()

elas = end_time- start_time
print(f"{elas:.10f}")

0.0000000000


In [24]:
import numpy as np

torch_rand1 = torch.rand(10000,10000).to(device)
torch_rand2 = torch.rand(10000,10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)
start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elas = end_time- start_time
print(f"{elas:.10f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elas = end_time - start_time
print(f"{elas:.10f}")

0.0543284416
0.1737270355


In [32]:
probabilities = torch.tensor([0.99,0.01])
samples = torch.multinomial(probabilities,num_samples= 10,replacement=True)
samples

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import torch.nn as nn
#Linear
import torch.nn.functional as F
#softmax
#embedded